//Exercise #1

# Modify Default Mule App Behavior

When a Mule app starts, a connectivity test runs on components, such as the HTTP or FTP connector. If the test fails, the system logs a warning message by default and continues with the app deployment.

To modify the default behavior:

* Set the Fail Deployment (`failsDeployment`) parameter to true. In this case, the deployment fails if the following conditions are met:

** The connection fails.
** Any configured reconnection attempts are exhausted.

* Set the Reconnect (`reconnect`) parameter to ''. In this case, the app limits the number of reconnection attempts and the interval to run them. 

+ In the following example, the application attempts to reconnect 
 5 times in every 4000 milliseconds (ms). The connection fails 
 after 5 reconnection attempts.

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection
  </http:request-connection>
</http:request-config>
----

* Set the Reconnect Forever (reconnect-forever) parameter to a desired interval. In this case, the app attempts to reconnect at the given interval.  

In the following example, the number of reconnection attempts is not set and the app attempts to reconnect every 4000 ms for as long as it runs.


[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
</http:request-config>
----
